import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';

await build({
  entryPoints: ['src/server/gas/main.ts'],
  bundle: true,
  format: 'iife',            // nothing leaks to global scope except main.ts's __sava namespace
  // target es2019, NOT es2020: the static scanner that builds google.script.run's callable
  // function list (and needs top-level declarations, hence stubs.js below) fails to parse
  // ES2020 optional-chaining (?.) / nullish-coalescing (??) and then registers NO functions
  // for the whole project — the deployed app fails with ".api is not a function" even though
  // the V8 runtime (editor Run, triggers) executes the same code fine. es2019 transpiles both
  // operators away, keeping the server files parseable by the scanner.
  target: 'es2019',
  outfile: 'dist/server.js',
  logLevel: 'info',
});

/**
 * dist/stubs.js — the five invocable global functions, as PLAIN ES5 declarations.
 *
 * Why a separate file: the static analyzer that builds the Apps Script function
 * registry (used by BOTH the editor's run dropdown and google.script.run's client
 * proxy) is more conservative than the V8 runtime and can choke on the bundled
 * server.js's modern syntax — when it does, it silently registers no functions and
 * google.script.run.api "is not a function" in the deployed web app. A tiny ES5-only
 * file is always parseable, so the registry always sees exactly these five names.
 *
 * Why delegation (not empty stubs overwritten by the bundle): reading
 * globalThis.__sava at CALL time makes the pattern independent of the order in
 * which GAS evaluates project files. By the time anything can invoke a stub, every
 * file has been evaluated and __sava holds the real implementations (main.ts).
 * Keep this list in sync with main.ts's __sava namespace.
 */
const STUBS = `// Generated by scripts/build-server.mjs — do not edit.
// Invocable surface of the app; implementations live in server.js's __sava namespace.
function doGet(e) { return globalThis.__sava.doGet(e); }
function api(request) { return globalThis.__sava.api(request); }
function setup() { return globalThis.__sava.setup(); }
function purgeSessions() { return globalThis.__sava.purgeSessions(); }
function weeklyBackup() { return globalThis.__sava.weeklyBackup(); }
`;
writeFileSync('dist/stubs.js', STUBS);
console.log('  dist/stubs.js emitted (ES5 delegating stubs)');
